### ISSUE TITLE
Bats is now a 'Donor'

### ISSUE THREAD

**Issue by alostuckop** [MST-ACM/ACM_Website#119]
Please add Bats at the correct level in our sponsors page.

**Comment by kevinschoonover** [comment]
@alostuckop Please add a description for Bats and if they have a preferred picture they want us to use; otherwise, we will pick one.

**Comment by alostuckop** [comment]
I have asked them to provide me with that information. Will update when it arrives.

**Comment by kevinschoonover** [comment]
Any progress @alostuckop

**Comment by kevinschoonover** [comment]
Fixed in bc54ff330baca9f25b98437069c93562bfc25b88
