### ISSUE TITLE
Attempt to gracefully scale all fliers

### ISSUE THREAD

**Issue by kevinschoonover** [MST-ACM/ACM_Website#74]
Mostly people will be submitting 81/2x11 fliers, but there are some cases where a user may not want to be constricted by that.

**Comment by ZachWileman** [comment]
Is the current state of what I showed you today good enough for this issue to be closed? @kevinschoonover

**Comment by kevinschoonover** [comment]
Yes.

On Aug 28, 2017 21:23, "Zachary Wileman" <notifications@github.com> wrote:

Is the current state of what I showed you today good enough for this issue
to be closed? @kevinschoonover <https://github.com/kevinschoonover>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sigdotcom/acm.mst.edu/issues/74#issuecomment-325535856>,
or mute the thread
