### ISSUE TITLE
Adding Fixtures

### ISSUE THREAD

**Issue by ZachWileman** [MST-ACM/ACM_Website#84]
Look into adding fixtures (adding initial data to the database) to prevent Django from running into migration/database errors when developers switch git branches.

This can become a bigger problem the farther along we get in the development process since databases will have to get wiped each time changes to a models occur and then someone switches branches.

This will involve (I think as of now) making sure that each time vagrant starts, that it:

1.) Destroys database
2.) Recreates database
3.) Loads in initial data with fixtures

Note: Anytime you're wanting data to get added to the initial data that gets loaded into the database, you will need to use the "manage.py dumpdata" command to add the data.

Probably will need to find a way to remove the migrations folders completely from developers computers when switching branches since they seem to be contributing to the problem as well. Since git ignores those files, when someone switches branches the folder stays in its same location but will get applied to the new branch that developer switched to when they run vagrant (which then makes Django migration calls).

Relavant articles:
- https://www.reddit.com/r/django/comments/24mma5/how_to_manage_switching_back_and_forth_between/
- https://stackoverflow.com/questions/32682293/django-migrations-workflow-with-multiple-dev-branches
- https://docs.djangoproject.com/en/1.11/howto/initial-data/
- https://code.djangoproject.com/wiki/Fixtures

**Comment by kevinschoonover** [comment]
Completed with migrations.
